### ISSUE TITLE
Doesn't compile in Arduino IDE 1.8.8

### ISSUE THREAD

**Issue by Prodical** [freemovers/ATTinyCore-with-Micronucleus#1]
Hi

I'd really like to get LTO working with my DigiSpark ATTiny85 clone - I need to optimise as much space as possible in the available RAM - and this seems like the only currently available option without a lot of head-scratching and messy tinkering under the hood.

I've installed Spence Konde's ATTinyCore v1.2.4 and it does compile with LTO enabled and saves ~7% of available program storage space.

But using the California STEAM v1.2.3 ATTiny85 (DigiSpark) board I get the following compile error:

_In file included from sketch/DigiSpark_FastLED_working.ino.cpp:1:0:
/Users/drx/Library/Arduino15/packages/ATTinyCore/hardware/avr/1.2.4/cores/tiny/Arduino.h:166:26: fatal error: pins_arduino.h: No such file or directory
 #include "pins_arduino.h"
                          ^
compilation terminated.
exit status 1
Error compiling for board ATtiny85 (DigiSpark)._

I tried changing the path in the Arduino.h file to ../../variants/tinyX5/pins_arduino.h but then I got the error:

_open /Users/drx/Library/Arduino15/packages/ATTinyCore/hardware/avr/1.2.4/variants/tinyX5_reverse: no such file or directory_

I made a copy of the 'tinyX4_reverse' folder and renamed it 'tinyX5_reverse' - I appreciate this is a bodge - but then I got the error:

_chmod: /Users/drx/Library/Arduino15/packages/californiasteam/hardware/avr/1.2.3/create_disassembler_listing.sh: No such file or directory_

and gave up.

I tried downgrading to Spence Konde's ATTinyCore v1.2.2 but get the same issues.

Any advice appreciated.

Best

Lewis

**Comment by Prodical** [comment]
SOLVED
I manually installed tomaskovacik's ATTinyCore - https://github.com/tomaskovacik/ATTinyCore/tree/Digistump - forked from SpenceKonde's ATTinyCore and it includes board type "ATtiny45/85 (micronucleus,Digispark)" and it compiles with LTO enabled - yay!
